### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake-blender#54]
I think we're ready for the next stable tag.

@SeanCurtis-TRI do you agree?

If yes, I'll work on it and start to make a playbook (it's only a few clicks).

**Comment by SeanCurtis-TRI** [comment]
To be perfectly frank, I don't have a strong sense one way or the other. I've not particularly felt that the system lends itself well to Drake's trajectory. The minor and revision are implicitly aren't supposed to trash APIs (but we do that a fair amount under our stability policy). But that is ostensibly what the leading zero buys us, right?

So, if this is merely about clearly delineating that we've landed a lot of major features since 0.1.0, then I think it's justified. I'd have to review the changes to see if this month makes more sense than last month or next month (I doubt it.) So, it feels kind of arbitrary.

What is your thinking?

**Comment by jwnimmer-tri** [comment]
My only thought was that once all of this repo's changes related to glTF passthru support are finished, then we should tag a release so that your friends can use a tagged version of it instead of a random git sha.

**Comment by jwnimmer-tri** [comment]
(Possibly it should be 0.1.1 instead of 0.2.0; I haven't looked into that yet.)

**Comment by SeanCurtis-TRI** [comment]
[sheepishly] I wasn't paying attention which repo I was looking at.  :) That gets buried up at the top really quickly.

With that "new" piece of information, 0.1.1 makes the most sense. We've not changed any apis or any features, really. What we've done is fixed a couple of bugs (how client-vs-server geometry is distinguished and how the rotation is performed). Neither of those are new tasks, merely better implementations.

**Comment by jwnimmer-tri** [comment]
https://github.com/RobotLocomotion/drake-blender/releases/tag/v0.1.1
